import type { Metadata } from "next";
import "./globals.css";

import "remixicon/fonts/remixicon.css";

import Header from "@/components/header";
import Subheader from "@/components/subheader";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru">
      <body>
        <div className="wrapper">
          <Header />

          <main>
            <Subheader />
            {children}
          </main>

          <Footer />
        </div>
      </body>
    </html>
  );
}
